language: python
python:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "make deps"
  - "make install"
# command to run tests
script: "make test"
