language: python
python:
  - "2.6"
  - "2.7"
install:
  - "make deps"
  - "make install"
before_script:
  - "pip install python-coveralls --use-mirrors"
script: "make test"
after_success:
  - "coveralls"
